export const pending = [
  {
    User: "John Doe",
    email: "john@gmail.com",
    "Risk Level": "High",
    "Trigger Reason": "IP Changed",
    "In Queue For": "10 days",
    "Data Added On": "14 Oct,2023",
    "Previously Reviewed": "yes",
    "complete date": "23aug,2023",
  },
  {
    User: "Jane Smith",
    email: "jane98@gmail.com",
    "Risk Level": "Medium",
    "Trigger Reason": "IP Changed",
    "In Queue For": "6 days",
    "Data Added On": "13 Oct,2023",
    "Previously Reviewed": "No",
  },
  {
    User: "Alice Johnson",
    email: "alice69@gmail.com",
    "Risk Level": "Low",
    "Trigger Reason": "IP Changed",
    "In Queue For": "3 days",
    "Data Added On": "2 Oct,2023",
    "Previously Reviewed": "yes",
    "complete date": "24may,2023",
  },
  {
    User: "Bob Williams",
    email: "bod56@gmail.com",
    "Risk Level": "High",
    "Trigger Reason": "FIFO",
    "In Queue For": "5 days",
    "Data Added On": "10 Oct,2023",
    "Previously Reviewed": "no",
  },
  {
    User: "Charlie Brown",
    email: "charlie@gmail.com",
    "Risk Level": "Medium",
    "Trigger Reason": "FIFO",
    "In Queue For": "1 days",
    "Data Added On": "18 Oct,2023",
    "Previously Reviewed": "yes",
    "complete date": "14may,2023",
  },
  {
    User: "David Davis",
    email: "david44@gmail.com",
    "Risk Level": "High",
    "Trigger Reason": "IP Change",
    "In Queue For": "4 days",
    "Data Added On": "16 Oct,2023",
    "Previously Reviewed": "no",
  },
];

export const completed = [
  {
    User: "John Doe",
    email: "john@gmail.com",
    "Action Reason": "Flagged",
    "Risk Level": "Medium",
    "Time To Close": "10 days",
    "Data Added On": "14 Oct,2023",
    "Action Taken By": "Pratik",
    mail: "pratik@onjuno",
  },
  {
    User: "Jane Smith",
    email: "jane98@gmail.com",
    "Action Reason": "SOI requested",
    "Risk Level": "Medium",
    "Time To Close": "6 days",
    "Data Added On": "13 Oct,2023",
    "Action Taken By": "Neil",
    mail: "neil@onjuno",
  },
  {
    User: "Alice Johnson",
    email: "alice69@gmail.com",
    "Action Reason": "Flagged",

    "Risk Level": "Low",

    "Time To Close": "3 days",
    "Data Added On": "2 Oct,2023",
    "Action Taken By": "Pratik",
    mail: "pratik@onjuno",
  },
  {
    User: "Bob Williams",
    email: "bod56@gmail.com",
    "Action Reason": "Flagged",

    "Risk Level": "Low",

    "Time To Close": "5 days",
    "Data Added On": "10 Oct,2023",
    "Action Taken By": "Neil",
    mail: "neil@onjuno",
  },
  {
    User: "Charlie Brown",
    email: "charlie@gmail.com",
    "Action Reason": "closed",

    "Risk Level": "Medium",

    "Time To Close": "1 days",
    "Data Added On": "18 Oct,2023",
    "Action Taken By": "Pratik",
    mail: "pratik@onjuno",
  },
  {
    User: "David Davis",
    email: "david44@gmail.com",
    "Action Reason": "Flagged",

    "Risk Level": "High",
    "Time To Close": "4 days",
    "Data Added On": "16 Oct,2023",
    "Action Taken By": "Neil",
    mail: "neil@onjuno",
  },
];
